# -*- mode: python ; coding: utf-8 -*-

import os

block_cipher = None

a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PyQt5.QtWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'cryptography',
        'cryptography.hazmat.primitives.ciphers.aead',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'qfluentwidgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # PyQt5 不需要的模块
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
        'PyQt5.QtNetwork',
        'PyQt5.QtWebEngine',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebEngineCore',
        'PyQt5.QtQuick',
        'PyQt5.QtQuickWidgets',
        'PyQt5.QtQml',
        'PyQt5.QtSql',
        'PyQt5.QtSvg',
        'PyQt5.QtSvgWidgets',
        'PyQt5.QtTest',
        'PyQt5.QtBluetooth',
        'PyQt5.QtNfc',
        'PyQt5.QtPositioning',
        'PyQt5.QtLocation',
        'PyQt5.QtSensors',
        'PyQt5.QtSerialPort',
        'PyQt5.QtWebChannel',
        'PyQt5.QtWebSockets',
        'PyQt5.QtHelp',
        'PyQt5.QtDesigner',
        'PyQt5.QtOpenGL',
        'PyQt5.QtPdf',
        'PyQt5.QtPdfWidgets',
        'PyQt5.Qt3DCore',
        'PyQt5.Qt3DRender',
        'PyQt5.Qt3DInput',
        'PyQt5.Qt3DLogic',
        'PyQt5.Qt3DExtras',
        'PyQt5.Qt3DAnimation',
        'PyQt5.QtCharts',
        'PyQt5.QtDataVisualization',
        'PyQt5.QtRemoteObjects',
        'PyQt5.QtTextToSpeech',
        'PyQt5.QtSerialBus',
        # Python 标准库不需要的模块
        'unittest',
        'email',
        'html.parser',
        'xml',
        'xmlrpc',
        'pydoc',
        'doctest',
        # 'argparse',  # 部分库间接依赖
        # 'difflib',
        # 'pdb',
        # 'profile',
        # 'pstats',
        # 'timeit',
        # 'trace',
        # 'zipfile',  # Python 内部依赖，不能排除
        # 'tarfile',
        # 'gzip',
        # 'bz2',
        # 'lzma',
        'ftplib',
        'imaplib',
        'smtplib',
        'poplib',
        'cgi',
        'cgitb',
        'wsgiref',
        'lib2to3',
        'tkinter',
        'turtledemo',
        'idlelib',
        'test',
        '_pytest',
        'pytest',
        'numpy',
        'pandas',
        'matplotlib',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PasswordManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico' if os.path.exists('assets/icon.ico') else None,
)
